// console.log(document);
// const PTag = document.getElementById("Hello");
// PTag.style.color = "red";
// PTag.style.backgroundColor = "blue";
// PTag.style.fontSize = "30px"

// // PTag.hidden = true;
// // PTag.hidden = false;

// // setInterval(() => {
// //     PTag.hidden = !PTag.hidden
// PTag.innerHTML = "<i>Hello JavaScript</i> <b>Wecode</b>";


// const myImage = document.getElementById("animalImage")
// myImage.style.height = "200px";
// myImage.style.width = "150px";

// document.getElementById("myText").textContent = "<b>Hello javaScript</b>"; // <b></b> Is Not Allow
// document.getElementsByClassName("test")[1].style.backgroundColor = "yellow"

// document.getElementsByTagName("span")[1].style.backgroundColor = 'green'

// document.querySelector("#myName").style.backgroundColor = "red"


// document.querySelector(".Wecode").style.backgroundColor = 'red'
// document.querySelectorAll(".Wecode")[1].style.backgroundColor = 'red'



// // console.log(document.getElementsByClassName("test"));   

