// function test() {
//     console.log("Hello");
// }

// function test2() {
//     console.log("Hello World");
// }

// function test3() {
//     console.log("Hello JavaScript");
// }

// function test4() {
//     console.log("Wecode Academy");
// }

// function test5() {
//     const data = document.getElementById("Hello").value.toUpperCase()
//     document.getElementById("Hello").value = data
//     console.log(data);
// }

// let count = 0;
// function test6() {
//     ++count
//     document.getElementById("number").textContent = count;

// }

// document.getElementById("Hello").addEventListener("click", () => {
//     alert("Wecode")
// })


// document.getElementById("one").addEventListener("click", () => {
//     const element = document.getElementById("first")
//     element.hidden = !element.hidden
// })

// document.getElementById("two").addEventListener('click', () => {
//     const element = document.getElementById("second")
//     element.hidden = !element.hidden
// })


// document.getElementById("three").addEventListener('click', () => {
//     const element = document.getElementById("third")
//     element.hidden = !element.hidden
// })

// setInterval(() => {
//     const element = document.getElementById("first")
//     element.hidden = !element.hidden
// }, 1000)


// setInterval(() => {
//     const element = document.getElementById("second")
//     element.hidden = !element.hidden
// }, 2000)

// setInterval(() => {
//     const element = document.getElementById("three")
//     element.hidden = !element.hidden
// }, 3000)


